
=== About

Example code from the https://www.manning.com/books/react-hooks-in-action[React Hooks in Action] book.


=== Run application

```
npm start
```

=== Chapter 2.2

```
git checkout rhia-ch02-02
```

=== Chapter 2.3

```
git checkout rhia-ch02-03
```

=== Chapter 3.1

```
git checkout rhia-ch03-01
```

=== Chapter 3.2

```
git checkout rhia-ch03-02
```

=== Chapter 3.2

```
git checkout rhia-ch03-03
```

=== Chapter 4.2

```
git checkout rhia-ch04-02
```

Run JSON server with `npx json-server --watch src/db.json --port 3001 --delay 3000` and React dev server 
with `npm start`.


=== Chapter 5.2

```
git checkout rhia-ch05-02
```

Run JSON server with `npx json-server --watch src/db.json --port 3001 --delay 3000` and React dev server
with `npm start`.


=== Chapter 5.3

```
git checkout rhia-ch05-03
```

Run JSON server with `npx json-server --watch src/db.json --port 3001 --delay 3000` and React dev server
with `npm start`.

=== Chapter 6.3

```
git checkout rhia-ch06-03
```

Run JSON server with `npx json-server --watch src/db.json --port 3001 --delay 3000` and React dev server
with `npm start`.

=== Chapter 6.4

```
git checkout rhia-ch06-04
```

Run JSON server with `npx json-server --watch src/db.json --port 3001 --delay 3000` and React dev server
with `npm start`.

=== Chapter 6.5

```
git checkout rhia-ch06-05
```

Run JSON server with `npx json-server --watch src/db.json --port 3001 --delay 3000` and React dev server
with `npm start`.
